export const books = [
  {
    id: "b1",
    title: "Thor: Ragnarok",
    description: "Marvel Comics Book",
    author: "Stan Lee",
    price: 1499,
    stock: 10,
  },
  {
    id: "b2",
    title: "Avengers: End Game",
    description: "Marvel Comics Book",
    author: "Stan Lee",
    price: 999,
    stock: 5,
  },
  {
    id: "b3",
    title: "Spiderman: No Way Home",
    description: "Marvel Comics Book",
    author: "Stan Lee",
    price: 555,
    stock: 22,
  },
  {
    id: "b4",
    title: "Moon Knight",
    description: "Marvel Comics Book",
    author: "Stan Lee",
    price: 777,
    stock: 3,
  },
  {
    id: "b5",
    title: "Avengers: Infinity War",
    description: "Marvel Comics Book",
    author: "Stan Lee",
    price: 1099,
    stock: 33,
  },
  {
    id: "b6",
    title: "The Batman",
    description: "DC Comics Book",
    author: "Malcolm Wheeler-Nicholson",
    price: 1099,
    stock: 33,
  },
  {
    id: "b7",
    title: "The Suicide Squad",
    description: "DC Comics Book",
    author: "Malcolm Wheeler-Nicholson",
    price: 1099,
    stock: 33,
  },
  {
    id: "b8",
    title: "Superman",
    description: "DC Comics Book",
    author: "Malcolm Wheeler-Nicholson",
    price: 1099,
    stock: 33,
  },
  {
    id: "b9",
    title: "Wonder woman",
    description: "DC Comics Book",
    author: "Malcolm Wheeler-Nicholson",
    price: 1099,
    stock: 33,
  },
  {
    id: "b10",
    title: "Flash",
    description: "DC Comics Book",
    author: "Malcolm Wheeler-Nicholson",
    price: 1099,
    stock: 33,
  },
  {
    id: "b11",
    title: "Morbious",
    author: "Stan Lee",
    price: 299,
    stock: 3,
  },
];
